### ISSUE TITLE
Does this framework process voxels ? 

### ISSUE THREAD

**Issue by emanhamed** [tmquan/PVR#2]

**Comment by tmquan** [comment]
Yes, it extracts per voxel 72 dimensional feature vector.

**Comment by emanhamed** [comment]
Is it accepting any format other than the .tif such as .obj or .ply ?

**Comment by tmquan** [comment]
I am not sure that I understand your issue well. 
But the code can read either .tif files or .raw files as long as they are unsigned integer 8 bit and regularly structure data (volumetric 3D data). 
It can not read mesh files or point cloud files.
